name: CMake

on:
    push:
        branches:
            - master
            - dev

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow#configuring-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install conan
      run: |
        sudo apt-get update
        sudo apt-get install qt5-default
        sudo apt-get install "libxcb*"
        sudo apt-get install xorg-dev
        sudo apt-get install python3-setuptools
        sudo pip3 install conan
    
    - name: Build project
      run: |
        conan remote add qt:bincrafters https://api.bintray.com/conan/bincrafters/public-conan
        mkdir build
        cd build
        conan install .. --build=missing
        cmake ..
        cmake --build .